INSERT INTO tb_state (id, name) VALUES
        (1,'Minas Gerais'),
        (2,'Rio de Janeiro'),
        (3,'São Paulo'),
        (4,'São Paulo'),
        (5,'Rio Grande do Sul'),
        (6,'Santa Catarina'),
        (7,'Paraná'),
        (8,'Bahia'),
        (9,'Pernambuco'),
        (10,'Ceará'),
        (11,'Pará'),
        (12,'Rio Grande do Norte'),
        (13,'Amazonas'),
        (14,'Espírito Santo'),
        (15,'Goiás'),
        (16,'Mato Grosso'),
        (17,'Mato Grosso do Sul'),
        (18,'Alagoas'),
        (19,'Sergipe'),
        (20,'Piauí'),
        (21,'Maranhão'),
        (22,'Paraíba'),
        (23,'Distrito Federal'),
        (24,'Rondônia'),
        (25,'Roraima'),
        (26,'Acre'),
        (27,'Amapá'),
        (28,'Tocantins');